# Generated by Django 5.0 on 2024-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
